# -*- Sh -*-
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias -g L="| less"
alias -g G="| grep -i"

function take {
  mkdir -p $@ && cd $@
}

function em {
  emacsclient -c -a'' -n -f ~/.emacs.d/server/server
}
